### ISSUE TITLE
Build Orcania with CMake

### ISSUE THREAD

**Issue by silvioprog** [babelouest/orcania#10]
Hi dudes.

I've tried to build [Ulfius](https://github.com/babelouest/ulfius) on Windows using [MinGW-w64](http://www.msys2.org) for [32](http://repo.msys2.org/distrib/i686/msys2-i686-20161025.exe) and [64](http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20161025.exe) bits, but I've got some difficult. First, I'm trying to compile its dependences, so Orcania was the first one. However, it doesn't have a building system, and all building are done by a make file only for Linux. After [this fix](https://github.com/silvioprog/orcania/commit/1de750a270f1c4f5ee8778bc071e17042f648dc0) I can generated the `.so` file on MinGW, so I just need to rename its extension to `.dll` and enjoy it. OK, we can add a "`mv`" in the current makefile and solve it, but now the question is: why not adopting a cross platform building system like [CMake](https://cmake.org/). Check some challenges:

* On Linux, all user's includes are installed in "/usr/local/include", on MinGW in "C:\msys32\mingw32\include" for 32 bits and "C:\msys32\mingw64\include" for 64 bits;
* On Linux, all user's shared and static libraries are installed in "/usr/local/lib", on MinGW in the static and shared libraries are installed in different directories, "\*\mingw\*\lib" (notice the asterisk are representing 32 and 64 respectively) for static and "\*\mingw\*\bin" for shared libraries, and both shared and static are installed by default on MinGW (Orcania's makefile just install the shared one);
* On Linux, we have some tools like `ldconfig`, but it is not available on MinGW because it is not necessary on Windows;
* On Linux, for a library called `mynicelibrary`, we have a file like `libmynicelibrary.so.N.N.N`, on Windows, it is called `libmynicelibrary-V.dll` (e.g: on Linux, `libmicrohttpd.so.12.46.0`, on Windows, `libmicrohttpd-12.dll`);
* Using only makefile, the easiest way to use third party library is installing its shared version, but, o Windows, it is very common to see stand-alone libraries (eg: libsqlite.dll, ftd2xx.dll etc.) without depending to download its dependances (libgcc.dll, zlib.dll, libwinpthread.dll etc. etc. etc.), we just distribute only one DLL file (eg: libulfius-V.dll).

I think there are other things that I don't remember now, but these ones above already make difficult to build Ulfius, Orcania etc.

So, what to you think about using some building system like CMake? I know autotools, but it is very hard to do even simple things with that, the CMake is easier and present in many popular GNU libraries too (LibVNC, libjwt, libcurl etc.).

-- 
Silvio Clécio

**Comment by babelouest** [comment]
I can imagine your distress :)

I think that having a CMake building system is a good idea, especially for multiple platform compilation. This was mentioned in https://github.com/babelouest/ulfius/issues/23 for example

Also, having like one library `libulfius-V.dll` that will include Orcania and Yder would be better, especially for those who need only Ulfius

I don't know if I will keep both build systems (Makefile and CMake) or just keep CMake eventually but we're not there yet.

Can you help me implementing the CMake system buuilding for Orcania/Yder/Ulfius? I'm not familiar with CMake yet.

**Comment by silvioprog** [comment]
Sure. :-) I'm leaving home now, but as soon as possible I'll show you the tools I've been using and how I created my CMake buildings. :-)

**Comment by babelouest** [comment]
Again, there's no rush on this, I prefer using as much time as we need to make a clean and nice install for new platforms.

**Comment by silvioprog** [comment]
I'm back. :-)

Regarding building systems, I used a lot autotools (influenced by MHD) in some libraries I've maintained, but these days I got big problems to do simple things, for example: downloading and using third party libraries. I also used a lot GIT sub-modules, but it isn't safe to use unstable version of any library, then I decided to use their stable version. [CMake offer a builtin feature to download files](https://cmake.org/cmake/help/latest/command/file.html) in build time, so we can download the stable version (eg. MHD from its FTP, libjwt from its release etc.) of all our third party libraries and make local cache improving the building speed in next builds. Anyway, before someone throws me a mouse, I have nothing against autotools, I like it, even being so difficult to use, but for new projects I'm totally inclined to use CMake. :-)
Some references I've found that we could use besides cmake doc: [libvnc cmake](https://github.com/LibVNC/libvncserver/blob/master/CMakeLists.txt) file; [third party examples](cmake-examples); [StackOverflow reference](https://stackoverflow.com/questions/17511496/how-to-create-a-shared-library-with-cmake); [step-by-step articles](https://mirkokiefer.com/cmake-by-example-f95eb47d45b1) etc.

About IDEs, I don't know how I would manage coding, building, debugging and profiling C projects without a good IDE. Before, I used CodeLite, Eclipse, CodeBlocks, NetBeans, Visual Studio, Emacs etc., but, after tested [JetBrains' CLion](https://www.jetbrains.com/clion), I left all other C IDEs. :-) CLion is a paid tool, but since it was built with open source projects, the JetBrains offers a free version of CLion for students or open source projects, with same features of the paid version (the company that I work got the paid version, so I compared it with a student version that I used some time ago and I checked they are same), it has also community support. I strongly recommend you to test it. See its main window on my Xubuntu and some commented features below:

![00](https://user-images.githubusercontent.com/1456829/34949003-89a73d5c-f9ed-11e7-939a-47e316c04e82.png)

Importing a C project to CLion and creating its initial CMake:

![01](https://user-images.githubusercontent.com/1456829/34949373-aed89fc0-f9ee-11e7-8cd5-b2340cafb3d1.png)

it will ask about the project sources:

![02](https://user-images.githubusercontent.com/1456829/34949423-d3f18e70-f9ee-11e7-8709-e2285ba0ac7d.png)

![03](https://user-images.githubusercontent.com/1456829/34949431-da0480ba-f9ee-11e7-9aa8-fbfdd608ebc1.png)

after done, we can build, debug and check memory leaks (with button to run our project with [valgrind](http://valgrind.org)).

Also, CLion offers some fixes before building a project, i.e at design time, take a look at I'm editing Orcania in it:

![01](https://user-images.githubusercontent.com/1456829/34949673-88de8c5c-f9ef-11e7-93a6-2a69f8f73241.png)

so, when we click on these bands, we are jumped to the source editor:

![02](https://user-images.githubusercontent.com/1456829/34949719-ad74c16c-f9ef-11e7-98d8-97a9af32c798.png)

that offers the Alt+F12 option:

![03](https://user-images.githubusercontent.com/1456829/34949731-bc7acd3c-f9ef-11e7-86ce-3853fc778811.png)

suggesting possible corrections:

![04](https://user-images.githubusercontent.com/1456829/34949748-c7bde760-f9ef-11e7-8780-43f78b19e67f.png)

or

![05](https://user-images.githubusercontent.com/1456829/34949774-dbf7ab08-f9ef-11e7-94a4-7cb83a3ee955.png)

without any building, all at design time. :-) ( sorry for many pictures ^^' )

I've used other CLion's features like builtin CMake code completion, Doxygen/markdown support, GIT/.ignore plugin, performance testing plugin and more.

The only thing that could sounds unfamiliar is because CLion uses the [Google C/C++ code style](https://google.github.io/styleguide/cppguide.html) by default (that is adopted by [NodeJS's libuv](https://github.com/libuv/libuv) too), but you can easily configure it to use others or your own code style.

Edit: we need to check the `ExternalProject_Add()` option showed in [this article](https://mirkokiefer.com/cmake-by-example-f95eb47d45b1). It seems a nice option to use with lib MHD and libjwt. :-)

**Comment by babelouest** [comment]
Thanks @silvioprog ,

I suggest we complete Orcania's CMake and MinGW patches before finishing Yder's, anyway Orcania is the lower-level library and has no dependencies on my other libraries, I think it's the best starting point to improve Ulfius' building system.

Concerning CLion, it seems an interesting tool but that's not relevant in Orania issues, I'd prefer the issues to focus on issues and not spread to other discussions, otherwise it will be harder to follow and if we have to go back in the future, it will be harder to understant what data is relevant or not.

**Comment by silvioprog** [comment]
> I suggest we complete Orcania's CMake and MinGW patches before finishing Yder's, anyway Orcania is the lower-level library and has no dependencies on my other libraries, I think it's the best starting point to improve Ulfius' building system.

Done. Finally Orcania can be built with CMake! :-) 

All steps below requires at least CMake 3.5.

Building and installing on Debian/Ubuntu from trunk:

```bash
git clone https://github.com/silvioprog/orcania.git
cd orcania/
git checkout cmake
mkdir build
cd build/
cmake ..
sudo make install/strip
```

Additional commands:

* use `sudo make install` if you want the debugging version
* use `pkg-config` to get library info, e.g: `pkg-config liborcania --libs`
* use `make test` to run all tests
* use `make dist` to generate a production `tag.gz` (we should use it to distribute stable [signed](https://www.gnupg.org/faq/gnupg-faq.html#common_commands) sources instead of trunk)
* use `make package` to generate `.deb/.rpm` packages

<hr>

Building and installing on Windows. Firstly, install MinGW-w64 from [msys2.org](http://www.msys2.org) and all tools you need to build Orcania with CMake:

```bash
pacman -S --needed git
pacman -S --needed base-devel
pacman -S --needed mingw-w64-i686-toolchain mingw-w64-x86_64-toolchain
pacman -S --needed mingw-w64-i686-cmake mingw-w64-x86_64-cmake
pacman -S --needed mingw-w64-i686-check mingw-w64-x86_64-check
```

Now, open the `MSYS2 MinGW 32-bit` (or `MSYS2 MinGW 64-bit` for 64 bits) command line and build Orcania for Windows:

```bash
git clone https://github.com/silvioprog/orcania.git
cd orcania/
git checkout cmake
mkdir build
cd build/
cmake -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=/mingw32 .. # or /mingw64
make install/strip
```

If you want the Ocania's DLL file, get it from `C:\msys32\mingw32\bin\liborcania-1.dll` and enjoy that!

Note: I'm using a temporary unofficial repo/branch, then all steps above may be changed as soon as cmake building was merged to the official trunk. :+1: 

Edit for Debian/Ubuntu users:

If you get some message "shared 'orcania' library not found", don't worry, just upgrade the libraries cache with `sudo ldconfig`.

**Comment by babelouest** [comment]
Hello @silvioprog ,

Thanks a lot for this amazing work! I've tested it on a fresh install and found out that there may be a problem regarding jansson dependency. This library is required for the full version or Orcania but I made it optional in the original `Makefile`.

The first problem is that the file `CMakeLists.txt` doesn't check if Jansson (including its header files) is installed, and also, to be compatible with the original `Makefile`, we should add an option to build Orcania without Jansson.

The way to build Orcania without Jansson in the original `Makefile` is:
```shell
$ make JANSSONFLAG=-DU_DISABLE_JANSSON
```

**Comment by silvioprog** [comment]
Hello dude, glad you like it! :-) 

You are right, and we need to check other required headers too (`string.h`, `stdarg.h` etc.). I'm going to upgrade it in the `CMakeLists.txt` ...

Regarding `JANSSONFLAG`, I'm going to check original `Makefile` to migrate it to CMake's [`option`](https://cmake.org/cmake/help/v3.10/command/option.html), so the users `cmake -DU_DISABLE_JANSSON=ON ..` [like this](https://stackoverflow.com/questions/18435516/how-to-set-a-cmake-option-at-command-line). :-)

**Comment by babelouest** [comment]
If possible, I'd name the disable jansson option with something more meaningful, something like `cmake jansson=off` for example...

**Comment by silvioprog** [comment]
`jansson=off` sounds good, it will be like this. :sunglasses:

**Comment by silvioprog** [comment]
[sharing] Interesting article: http://voices.canonical.com/jussi.pakkanen/2013/03/26/a-list-of-common-cmake-antipatterns . I'm reading it to apply to Orcania building ...

**Comment by silvioprog** [comment]
Finally I finished our cmake building! :-) 

I'm just waiting this issue to commit my last changes: https://github.com/nghttp2/nghttp2/issues/1113 .

Now we can build Orcania even missing `libcheck` or `libjansson` on the system.

**Comment by silvioprog** [comment]
Hi again @babelouest . :-)

I've made many changes and now it supports the following options appended to the `cmake ..`:

* [`-DWITH_JANSSON=ON/OFF`](https://stackoverflow.com/questions/15201064/cmake-conditional-preprocessor-define-on-code) - enable/disable jansson using;
* [`-DBUILD_TESTING=ON/OFF`](https://cmake.org/cmake/help/v3.0/module/CTest.html?highlight=build_testing) - enable/disable tests.

The `WITH_JANSSON=ON` will declare the define `USE_JANSSON` internally using jansson library. `BUILD_TESTING=ON` will enable all supported tests. The Orcania's building auto detects which libraries are available in the system enabling/disabling these options automatically, so I think it may work fine in a fresh system.

**Comment by babelouest** [comment]
You're awesome!

One last change and I think we'll be ready to merge, can you set the parameter `-DBUILD_TESTING` to OFF by default? So `check` won't be necessary for normal everyday install.

**Comment by silvioprog** [comment]
Done! :+1: :sunglasses: :+1:

**Comment by babelouest** [comment]
Like a boss

**Comment by babelouest** [comment]
Can you send a Pull Request to the my branch?

**Comment by silvioprog** [comment]
Sure. :smiley: I'm going to send it ...

**Comment by babelouest** [comment]
Thanks, as I said in the pull request, there are too much changes for a new feature that shouldn't require that much.

The way I see Orcania and all my other tools is that they are fitted for Makefile first. Using other build tools is OK as long as it doesn't change the library intent: to be available on small and embedded devices, without huge dependencies.

I hope the changes I require are OK to you.

**Comment by silvioprog** [comment]
Hello dude. I'm going to do the changes as requested, but they are really required to compile with `-Wall`/`-Wextra`/`-Werror` (could you try to compile with these options?). Regarding makefiles I just deleted it because your previous comment about removing them, but they will be restored. :-) Regarding `O_EXTERN` I'll try to explain at https://github.com/babelouest/orcania/pull/11#discussion_r162797096 .

**Comment by silvioprog** [comment]
Done in a new temporary fork/branch: https://github.com/silvioprog/orcania/commits/cmake . :sunglasses:
