### ISSUE TITLE
cosmetic fix

### ISSUE THREAD

**Issue by silvioprog** [babelouest/orcania#14]
Please update repo description from "... among c programs" to "... among C programs":

<hr>

![screenshot_2018-01-24_21-55-17](https://user-images.githubusercontent.com/1456829/35365094-69716466-0151-11e8-94f6-76355326c9e4.png)

**Comment by babelouest** [comment]
Thanks!

**Comment by silvioprog** [comment]
![image](https://user-images.githubusercontent.com/1456829/35366158-bdd2a920-0156-11e8-96d9-192c04efcfb8.png)

:grin:

**Comment by babelouest** [comment]
It's fixed in the cmake branch, sorry 😅

**Comment by silvioprog** [comment]
oopss indeed :sweat_smile:
