### ISSUE TITLE
Building with U_DISABLE_JANSSON & make is failing

### ISSUE THREAD

**Issue by Ryceancurry** [babelouest/orcania#19]
Looks like we getting redefining of U_DISABLE_JANSSON.

jc957059@stbirv-lnx-2:/local/users/jc957059/probes/ejtag/app/rest/orcania$ make JANSSONFLAG=-DU_DISABLE_JANSSON
cd ./src && make
make[1]: Entering directory '/local/users/jc957059/probes/ejtag/app/rest/orcania/src'
Config file ../include/orcania-cfg.h generated
gcc -c -fPIC -Wall -Werror -Wextra -I../include -D_REENTRANT -O3 -DU_DISABLE_JANSSON  memory.c
In file included from ../include/orcania.h:30:0,
                 from memory.c:12:
../include/orcania-cfg.h:31:0: error: "U_DISABLE_JANSSON" redefined [-Werror]
 #define U_DISABLE_JANSSON
 ^
<command-line>:0:0: note: this is the location of the previous definition
cc1: all warnings being treated as errors
Makefile:60: recipe for target 'memory.o' failed

**Comment by babelouest** [comment]
Thanks for noticing!

I will add the `Makefile` build in the CI script to validate this then.
