### ISSUE TITLE
compilation warning

### ISSUE THREAD

**Issue by harihanv** [babelouest/orcania#2]
orcania.c: In function ‘trimwhitespace’:
orcania.c:382:3: warning: implicit declaration of function ‘isspace’ [-Wimplicit-function-declaration]
   while(isspace((unsigned char)*str)) str++;
   ^
gcc -shared -Wl,-soname,liborcania.so -o liborcania.so.0.8 orcania.o -lc -ljansson

I am getting this warning, 
I was able to overcome this error by including ctype.h

**Comment by babelouest** [comment]
That's right, forgot about this little one, thanks for the help :)

Should be fixed now.
