### ISSUE TITLE
Build bugs

### ISSUE THREAD

**Issue by dlblv** [babelouest/orcania#21]
Hey! It's me who is about cross-compiling your libs for armv7l :)

New makefile deploys new build error: 

`make: *** No rule to make target 'liborcania.so', needed by 'all'.  Stop.`

How to reproduce:

1. git clone 
2. git checkout v1.2.9
3. make

**Comment by babelouest** [comment]
Fixed in master branch, thanks!

**Comment by dlblv** [comment]
> Fixed in master branch, thanks!

Thank **you**!
