### ISSUE TITLE
Is math library really needed?

### ISSUE THREAD

**Issue by madebr** [babelouest/orcania#31]
`base64.c` includes `math.h`:

https://github.com/babelouest/orcania/blob/b01c4f1d6b7a7d26ab9a9392406f0d5ac920b4b2/src/base64.c#L10

and the cmake scripts adds `m` to the linked libraries:

https://github.com/babelouest/orcania/blob/b01c4f1d6b7a7d26ab9a9392406f0d5ac920b4b2/CMakeLists.txt#L34

But is it really needed? Disabling both keeps orcania building on MSVC without any extra warnings.

**Comment by babelouest** [comment]
Indeed, it seems to be a either a mistake, or a leftover from an old time.

**Comment by babelouest** [comment]
Thanks @madebr !
