### ISSUE TITLE
What does orcania mean ?

### ISSUE THREAD

**Issue by auxeon** [babelouest/orcania#33]
At first I thought it was a mis-spelling of ```Ocarina``` the music instrument - @babelouest what does ```orcania``` mean - and why did you name this repository so ?

**Comment by babelouest** [comment]
Hello,

This library has this name because for some obscure reason, I use names taken from the Arthurian Legend for my projects, and `Orcania` is the name [King Lot](https://en.wikipedia.org/wiki/King_Lot)'s kingdom in this legend.

It has nothing to do with the music instrument, sorry...
