### ISSUE TITLE
Release 2.3.3 misnumbered as 2.2.3

### ISSUE THREAD

**Issue by brechtsanders** [babelouest/orcania#34]
Release 2.3.3 seems to be misnumbered as 2.2.3
https://github.com/babelouest/orcania/releases/tag/v2.2.3

**Comment by nunotexbsd** [comment]
And why not switch to release assets?

https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/

**Comment by babelouest** [comment]
Indeed, thanks!

**Comment by babelouest** [comment]
About the release assets, I'll have a look at that for the future releases, thanks @nunotexbsd
