### ISSUE TITLE
[DOC REQUEST] building orcania on MinGW

### ISSUE THREAD

**Issue by silvioprog** [babelouest/orcania#9]
Could you please assign this task for me? :sunglasses:

**Comment by babelouest** [comment]
Sure :)

**Comment by silvioprog** [comment]
Now CMake users can build Orcania easily if applying these two commits: https://github.com/babelouest/orcania/pull/11#issuecomment-359278057 in their copy. No document required, just:

* `mkdir build && cd build/ && cmake .. && make install/strip` (`sudo make install/strip` on Linux) to install the library

or:

* `mkdir build && cd build/ && cmake .. -DBUILD_TESTING=ON && make test` to run the tests

the only additional note for Windows is to append `-DCMAKE_INSTALL_PREFIX=/mingw32` or `-DCMAKE_INSTALL_PREFIX=/mingw64` to avoid installing the DLL into mingw directory instead of the "program and files" one.
